# fly.toml app configuration file generated for huddlz on 2025-08-16T17:10:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'huddlz'
primary_region = 'iad'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = "/bin/sh -lc 'DATABASE_URL=$DIRECT_DATABASE_URL POOL_SIZE=2 /app/bin/migrate'"

[env]
  PHX_HOST = 'huddlz.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '15s'
    method = 'GET'
    path = '/healthz'
    timeout = '5s'

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
