defmodule Huddlz.Repo.Migrations.AddGroupImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      remove :image_url
    end

    create table(:group_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text, null: false
      add :content_type, :text, null: false
      add :size_bytes, :bigint, null: false
      add :storage_path, :text, null: false
      add :thumbnail_path, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :deleted_at, :utc_datetime_usec

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_images_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:group_images, [:group_id, :inserted_at])

    create unique_index(:group_images, [:storage_path],
             name: "group_images_unique_storage_path_index"
           )
  end

  def down do
    drop_if_exists unique_index(:group_images, [:storage_path],
                     name: "group_images_unique_storage_path_index"
                   )

    drop constraint(:group_images, "group_images_group_id_fkey")

    drop_if_exists index(:group_images, [:group_id, :inserted_at])

    drop table(:group_images)

    alter table(:groups) do
      add :image_url, :text
    end
  end
end
