defmodule Huddlz.Repo.Migrations.UpdateUserDisplayNameConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Backfill existing null display names with email prefix
    execute """
    UPDATE users
    SET display_name = SPLIT_PART(email, '@', 1)
    WHERE display_name IS NULL OR display_name = ''
    """

    alter table(:users) do
      modify :display_name, :text, null: false
    end
  end

  def down do
    alter table(:users) do
      modify :display_name, :text, null: true
    end
  end
end
