defmodule Huddlz.Repo.Migrations.RemoveUniqueHuddlNameByCreator do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:huddlz, [:creator_id, :title],
                     name: "huddlz_unique_title_per_creator_index"
                   )
  end

  def down do
    create unique_index(:huddlz, [:creator_id, :title],
             name: "huddlz_unique_title_per_creator_index"
           )
  end
end
