defmodule Huddlz.Repo.Migrations.AddHuddlImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:huddl_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text, null: false
      add :content_type, :text, null: false
      add :size_bytes, :bigint, null: false
      add :storage_path, :text, null: false
      add :thumbnail_path, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :deleted_at, :utc_datetime_usec

      add :huddl_id,
          references(:huddlz,
            column: :id,
            name: "huddl_images_huddl_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:huddl_images, [:huddl_id, :inserted_at])

    create unique_index(:huddl_images, [:storage_path],
             name: "huddl_images_unique_storage_path_index"
           )
  end

  def down do
    drop_if_exists unique_index(:huddl_images, [:storage_path],
                     name: "huddl_images_unique_storage_path_index"
                   )

    drop constraint(:huddl_images, "huddl_images_huddl_id_fkey")

    drop_if_exists index(:huddl_images, [:huddl_id, :inserted_at])

    drop table(:huddl_images)
  end
end
