defmodule Huddlz.Repo.Migrations.CreateHuddlTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:huddl_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :repeat_until, :utc_datetime, null: false
      add :frequency, :text, null: false, default: "weekly"
    end
  end

  def down do
    drop table(:huddl_templates)
  end
end
