defmodule Huddlz.Repo.Migrations.AddProfilePictures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profile_pictures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text, null: false
      add :content_type, :text, null: false
      add :size_bytes, :bigint, null: false
      add :storage_path, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "profile_pictures_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:profile_pictures, [:user_id, :inserted_at])

    create unique_index(:profile_pictures, [:storage_path],
             name: "profile_pictures_unique_storage_path_index"
           )
  end

  def down do
    drop_if_exists unique_index(:profile_pictures, [:storage_path],
                     name: "profile_pictures_unique_storage_path_index"
                   )

    drop constraint(:profile_pictures, "profile_pictures_user_id_fkey")

    drop_if_exists index(:profile_pictures, [:user_id, :inserted_at])

    drop table(:profile_pictures)
  end
end
