defmodule Huddlz.Repo.Migrations.AddLocationPreferencesToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :default_location, :geometry
      add :default_location_address, :text
      add :default_search_radius, :bigint, default: 25
    end

    create index(:users, [:default_location], using: "GIST")
  end

  def down do
    alter table(:users) do
      remove :default_search_radius
      remove :default_location_address
      remove :default_location
    end
  end
end
