defmodule Huddlz.Repo.Migrations.AddHuddlAttendees do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:huddl_attendees, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :rsvped_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :huddl_id,
          references(:huddlz,
            column: :id,
            name: "huddl_attendees_huddl_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "huddl_attendees_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:huddl_attendees, [:huddl_id, :user_id],
             name: "huddl_attendees_unique_huddl_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:huddl_attendees, [:huddl_id, :user_id],
                     name: "huddl_attendees_unique_huddl_user_index"
                   )

    drop constraint(:huddl_attendees, "huddl_attendees_huddl_id_fkey")

    drop constraint(:huddl_attendees, "huddl_attendees_user_id_fkey")

    drop table(:huddl_attendees)
  end
end
