defmodule Huddlz.Repo.Migrations.MakeGroupImageGroupIdNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_images) do
      modify :group_id, :uuid, null: true
    end

    # Partial index for efficient orphan cleanup queries
    create index(:group_images, [:inserted_at],
             where: "group_id IS NULL",
             name: "group_images_orphaned_cleanup_index"
           )
  end

  def down do
    drop_if_exists index(:group_images, name: "group_images_orphaned_cleanup_index")

    # Delete any pending images before making group_id non-nullable
    execute "DELETE FROM group_images WHERE group_id IS NULL"

    alter table(:group_images) do
      modify :group_id, :uuid, null: false
    end
  end
end
