defmodule Huddlz.Repo.Migrations.CreateUserAddresses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :formatted_address, :text, null: false
      add :latitude, :decimal, null: false, precision: 10, scale: 7
      add :longitude, :decimal, null: false, precision: 10, scale: 7
      add :street_number, :text
      add :street_name, :text
      add :city, :text
      add :state, :text
      add :postal_code, :text
      add :country, :text
      add :country_name, :text
      add :place_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_addresses_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:user_addresses, [:country])

    create index(:user_addresses, [:state])

    create index(:user_addresses, [:city])

    create index(:user_addresses, [:latitude, :longitude])

    create index(:user_addresses, [:user_id])

    create unique_index(:user_addresses, [:user_id], name: "user_addresses_unique_user_index")
  end

  def down do
    drop_if_exists unique_index(:user_addresses, [:user_id],
                     name: "user_addresses_unique_user_index"
                   )

    drop constraint(:user_addresses, "user_addresses_user_id_fkey")

    drop_if_exists index(:user_addresses, [:user_id])

    drop_if_exists index(:user_addresses, [:latitude, :longitude])

    drop_if_exists index(:user_addresses, [:city])

    drop_if_exists index(:user_addresses, [:state])

    drop_if_exists index(:user_addresses, [:country])

    drop table(:user_addresses)
  end
end
