defmodule Huddlz.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :display_name, :text
    end
  end

  def down do
    alter table(:users) do
      remove :display_name
    end
  end
end
