defmodule Huddlz.Repo.Migrations.SimplifyUserRoles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # First update all regular and verified users to user role
    execute "UPDATE users SET role = 'user' WHERE role IN ('verified', 'regular')"

    # Then modify the column default
    alter table(:users) do
      modify :role, :text, default: "user"
    end
  end

  def down do
    alter table(:users) do
      modify :role, :text, default: "regular"
    end
  end
end
