defmodule Huddlz.Repo.Migrations.AddHuddlTemplateToHuddlz do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :huddl_template_id,
          references(:huddl_templates,
            column: :id,
            name: "huddlz_huddl_template_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:huddlz, "huddlz_huddl_template_id_fkey")

    alter table(:huddlz) do
      remove :huddl_template_id
    end
  end
end
