defmodule Huddlz.Repo.Migrations.ChangeGroupNameAndDescriptionToCiString do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      modify :description, :citext
      modify :name, :citext
    end
  end

  def down do
    alter table(:groups) do
      modify :name, :text
      modify :description, :text
    end
  end
end
