defmodule Huddlz.Repo.Migrations.AddPostgisAndCoordinates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :coordinates, :geometry
    end
  end

  def down do
    alter table(:huddlz) do
      remove :coordinates
    end
  end
end
