defmodule Huddlz.Repo.Migrations.AddThumbnailToProfilePictures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:profile_pictures) do
      add :thumbnail_path, :text
    end
  end

  def down do
    alter table(:profile_pictures) do
      remove :thumbnail_path
    end
  end
end
