defmodule Huddlz.Repo.Migrations.RequireGroupAndHuddlTimeZones do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      add :time_zone, :text
    end

    execute "UPDATE groups SET time_zone = 'America/New_York' WHERE time_zone IS NULL"
    execute "UPDATE huddlz SET time_zone = 'America/New_York' WHERE time_zone IS NULL"

    alter table(:groups) do
      modify :time_zone, :text, null: false
    end

    alter table(:huddlz) do
      modify :time_zone, :text, null: false
    end
  end

  def down do
    alter table(:huddlz) do
      modify :time_zone, :text, null: true
    end

    alter table(:groups) do
      remove :time_zone
    end
  end
end
