defmodule Huddlz.Repo.Migrations.SharedAuditCoverage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_keys_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "api_keys_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "api_keys_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:api_keys_versions, [:version_inserted_at])

    create table(:group_images_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "group_images_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "group_images_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:group_images_versions, [:version_inserted_at])

    create table(:group_invitations_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "group_invitations_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "group_invitations_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:group_invitations_versions, [:version_inserted_at])

    create table(:group_locations_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "group_locations_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "group_locations_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:group_locations_versions, [:version_inserted_at])

    create table(:group_members_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "group_members_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "group_members_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:group_members_versions, [:version_inserted_at])

    create table(:groups_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "groups_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "groups_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:groups_versions, [:version_inserted_at])

    create table(:huddl_attendees_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "huddl_attendees_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "huddl_attendees_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:huddl_attendees_versions, [:version_inserted_at])

    create table(:huddl_cover_images_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "huddl_cover_images_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "huddl_cover_images_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:huddl_cover_images_versions, [:version_inserted_at])

    create table(:huddl_photos_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "huddl_photos_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "huddl_photos_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:huddl_photos_versions, [:version_inserted_at])

    create table(:huddl_templates_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "huddl_templates_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "huddl_templates_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:huddl_templates_versions, [:version_inserted_at])

    create table(:profile_pictures_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "profile_pictures_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "profile_pictures_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:profile_pictures_versions, [:version_inserted_at])

    create table(:users_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "users_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "users_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:users_versions, [:version_inserted_at])
  end

  def down do
    drop_if_exists index(:users_versions, [:version_inserted_at])

    drop constraint(:users_versions, "users_versions_actor_id_fkey")

    drop constraint(:users_versions, "users_versions_impersonator_id_fkey")

    drop table(:users_versions)

    drop_if_exists index(:profile_pictures_versions, [:version_inserted_at])

    drop constraint(:profile_pictures_versions, "profile_pictures_versions_actor_id_fkey")

    drop constraint(:profile_pictures_versions, "profile_pictures_versions_impersonator_id_fkey")

    drop table(:profile_pictures_versions)

    drop_if_exists index(:huddl_templates_versions, [:version_inserted_at])

    drop constraint(:huddl_templates_versions, "huddl_templates_versions_actor_id_fkey")

    drop constraint(:huddl_templates_versions, "huddl_templates_versions_impersonator_id_fkey")

    drop table(:huddl_templates_versions)

    drop_if_exists index(:huddl_photos_versions, [:version_inserted_at])

    drop constraint(:huddl_photos_versions, "huddl_photos_versions_actor_id_fkey")

    drop constraint(:huddl_photos_versions, "huddl_photos_versions_impersonator_id_fkey")

    drop table(:huddl_photos_versions)

    drop_if_exists index(:huddl_cover_images_versions, [:version_inserted_at])

    drop constraint(:huddl_cover_images_versions, "huddl_cover_images_versions_actor_id_fkey")

    drop constraint(
           :huddl_cover_images_versions,
           "huddl_cover_images_versions_impersonator_id_fkey"
         )

    drop table(:huddl_cover_images_versions)

    drop_if_exists index(:huddl_attendees_versions, [:version_inserted_at])

    drop constraint(:huddl_attendees_versions, "huddl_attendees_versions_actor_id_fkey")

    drop constraint(:huddl_attendees_versions, "huddl_attendees_versions_impersonator_id_fkey")

    drop table(:huddl_attendees_versions)

    drop_if_exists index(:groups_versions, [:version_inserted_at])

    drop constraint(:groups_versions, "groups_versions_actor_id_fkey")

    drop constraint(:groups_versions, "groups_versions_impersonator_id_fkey")

    drop table(:groups_versions)

    drop_if_exists index(:group_members_versions, [:version_inserted_at])

    drop constraint(:group_members_versions, "group_members_versions_actor_id_fkey")

    drop constraint(:group_members_versions, "group_members_versions_impersonator_id_fkey")

    drop table(:group_members_versions)

    drop_if_exists index(:group_locations_versions, [:version_inserted_at])

    drop constraint(:group_locations_versions, "group_locations_versions_actor_id_fkey")

    drop constraint(:group_locations_versions, "group_locations_versions_impersonator_id_fkey")

    drop table(:group_locations_versions)

    drop_if_exists index(:group_invitations_versions, [:version_inserted_at])

    drop constraint(:group_invitations_versions, "group_invitations_versions_actor_id_fkey")

    drop constraint(
           :group_invitations_versions,
           "group_invitations_versions_impersonator_id_fkey"
         )

    drop table(:group_invitations_versions)

    drop_if_exists index(:group_images_versions, [:version_inserted_at])

    drop constraint(:group_images_versions, "group_images_versions_actor_id_fkey")

    drop constraint(:group_images_versions, "group_images_versions_impersonator_id_fkey")

    drop table(:group_images_versions)

    drop_if_exists index(:api_keys_versions, [:version_inserted_at])

    drop constraint(:api_keys_versions, "api_keys_versions_actor_id_fkey")

    drop constraint(:api_keys_versions, "api_keys_versions_impersonator_id_fkey")

    drop table(:api_keys_versions)
  end
end
