defmodule Huddlz.Repo.Migrations.StoreRecurringWallClockSchedule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddl_templates) do
      add :starts_at_local, :naive_datetime
      add :ends_at_local, :naive_datetime
      add :time_zone, :text
    end

    execute """
    UPDATE huddl_templates AS templates
    SET starts_at_local =
          (source.starts_at AT TIME ZONE 'UTC') AT TIME ZONE source.time_zone,
        ends_at_local =
          (source.ends_at AT TIME ZONE 'UTC') AT TIME ZONE source.time_zone,
        time_zone = source.time_zone
    FROM huddlz AS source
    WHERE source.id = (
      SELECT candidate.id
      FROM huddlz AS candidate
      WHERE candidate.huddl_template_id = templates.id
      ORDER BY candidate.starts_at ASC
      LIMIT 1
    )
    """

    execute """
    UPDATE huddl_templates
    SET starts_at_local = repeat_until,
        ends_at_local = repeat_until + INTERVAL '1 hour',
        time_zone = 'America/New_York'
    WHERE starts_at_local IS NULL
    """

    alter table(:huddl_templates) do
      modify :starts_at_local, :naive_datetime, null: false
      modify :ends_at_local, :naive_datetime, null: false
      modify :time_zone, :text, null: false
    end
  end

  def down do
    alter table(:huddl_templates) do
      remove :time_zone
      remove :ends_at_local
      remove :starts_at_local
    end
  end
end
