defmodule Huddlz.Repo.Migrations.RecordCopyMeasurementStart do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:copy_measurement, primary_key: false) do
      add :id, :bigint, null: false, default: 1, primary_key: true
      add :started_at, :utc_datetime_usec, null: false
    end

    execute("""
    INSERT INTO copy_measurement (id, started_at) VALUES (1, (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'))
    """)
  end

  def down do
    execute("""
    DELETE FROM copy_measurement WHERE id = 1
    """)

    drop table(:copy_measurement)
  end
end
