defmodule Huddlz.Repo.Migrations.AddDropInReminders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:drop_in_reminders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :emailed_at, :utc_datetime_usec
      add :dismissed_at, :utc_datetime_usec
      add :closed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "drop_in_reminders_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "drop_in_reminders_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:drop_in_reminders, [:group_id, :user_id],
             name: "drop_in_reminders_unique_group_user_index"
           )

    create index(:drop_in_reminders, [:user_id])
  end

  def down do
    drop_if_exists index(:drop_in_reminders, [:user_id])

    drop constraint(:drop_in_reminders, "drop_in_reminders_user_id_fkey")

    drop constraint(:drop_in_reminders, "drop_in_reminders_group_id_fkey")

    drop_if_exists unique_index(:drop_in_reminders, [:group_id, :user_id],
                     name: "drop_in_reminders_unique_group_user_index"
                   )

    drop table(:drop_in_reminders)
  end
end
