defmodule Huddlz.Repo.Migrations.SocialPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:social_posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :occasion, :text, null: false
      add :due_at, :utc_datetime, null: false
      add :state, :text, null: false, default: "scheduled"
      add :sent_at, :utc_datetime_usec
      add :previous_starts_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :social_connection_id,
          references(:social_connections,
            column: :id,
            name: "social_posts_social_connection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :huddl_id,
          references(:huddlz,
            column: :id,
            name: "social_posts_huddl_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:social_posts, [:social_connection_id, :huddl_id, :occasion],
             name: "social_posts_unique_occasion_index",
             where: "(occasion <> 'moved')"
           )
  end

  def down do
    drop constraint(:social_posts, "social_posts_huddl_id_fkey")

    drop constraint(:social_posts, "social_posts_social_connection_id_fkey")

    drop_if_exists unique_index(:social_posts, [:social_connection_id, :huddl_id, :occasion],
                     name: "social_posts_unique_occasion_index"
                   )

    drop table(:social_posts)
  end
end
