defmodule Huddlz.Repo.Migrations.AddAccountSuspension do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :suspended_at, :utc_datetime_usec
      add :suspension_reason, :text

      add :suspended_by_id,
          references(:users,
            column: :id,
            name: "users_suspended_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:users, "users_suspended_by_id_fkey")

    alter table(:users) do
      remove :suspended_by_id
      remove :suspension_reason
      remove :suspended_at
    end
  end
end
