defmodule Huddlz.Repo.Migrations.AddUserThemePreference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :theme_preference, :text, null: false, default: "system"
    end
  end

  def down do
    alter table(:users) do
      remove :theme_preference
    end
  end
end
