defmodule Huddlz.Repo.Migrations.AddHomeLocationTimeZone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :home_time_zone, :text
    end

    execute """
    UPDATE users
    SET home_time_zone = 'America/New_York'
    WHERE home_location IS NOT NULL AND home_time_zone IS NULL
    """
  end

  def down do
    alter table(:users) do
      remove :home_time_zone
    end
  end
end
