defmodule Huddlz.Repo.Migrations.RecordUserSignups do
  @moduledoc """
  Records when each account was created. Accounts from before this column
  existed take their confirmation time as the closest thing on record, and
  the unconfirmed ones the time the migration ran. Both are explicitly
  marked as estimates, so they cannot be mistaken for recorded sign-ups.

  The column itself was autogenerated with `mix ash_postgres.generate_migrations`.
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :signup_date_source, :text, null: false, default: "recorded"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute """
    UPDATE users
    SET inserted_at = COALESCE(confirmed_at, inserted_at),
        signup_date_source = CASE WHEN confirmed_at IS NULL THEN 'migration' ELSE 'confirmation' END
    """
  end

  def down do
    alter table(:users) do
      remove :signup_date_source
      remove :inserted_at
    end
  end
end
