defmodule Huddlz.Repo.Migrations.BoundlessRecurrence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddl_templates) do
      add :source_huddl_id,
          references(:huddlz,
            column: :id,
            name: "huddl_templates_source_huddl_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      modify :repeat_until, :utc_datetime, null: true
    end

    # Existing series predate the source pointer. Point each at its earliest
    # occurrence, which is the huddl its series was created from.
    execute("""
    UPDATE huddl_templates AS t
    SET source_huddl_id = earliest.id
    FROM (
      SELECT DISTINCT ON (huddl_template_id) huddl_template_id, id
      FROM huddlz
      WHERE huddl_template_id IS NOT NULL
      ORDER BY huddl_template_id, starts_at ASC
    ) AS earliest
    WHERE t.id = earliest.huddl_template_id
    """)
  end

  def down do
    drop constraint(:huddl_templates, "huddl_templates_source_huddl_id_fkey")

    alter table(:huddl_templates) do
      modify :repeat_until, :utc_datetime, null: false
      remove :source_huddl_id
    end
  end
end
