defmodule Huddlz.Repo.Migrations.SharedAuditHistory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:huddlz_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :impersonation_id, :uuid

      add :impersonator_id,
          references(:users,
            column: :id,
            name: "huddlz_versions_impersonator_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :automatic?, :boolean
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "huddlz_versions_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:huddlz_versions, [:version_inserted_at])
  end

  def down do
    drop_if_exists index(:huddlz_versions, [:version_inserted_at])

    drop constraint(:huddlz_versions, "huddlz_versions_actor_id_fkey")

    drop constraint(:huddlz_versions, "huddlz_versions_impersonator_id_fkey")

    drop table(:huddlz_versions)
  end
end
