defmodule Huddlz.Repo.Migrations.AllowDistinctAddressBookUnits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:group_locations, [:group_id, :name],
                     name: "group_locations_unique_name_per_group_index"
                   )

    create unique_index(:group_locations, [:group_id, :name, :unit],
             name: "group_locations_unique_name_and_unit_per_group_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(:group_locations, [:group_id, :name, :unit],
                     name: "group_locations_unique_name_and_unit_per_group_index"
                   )

    create unique_index(:group_locations, [:group_id, :name],
             name: "group_locations_unique_name_per_group_index",
             nulls_distinct: false
           )
  end
end
