defmodule Huddlz.Repo.Migrations.PendingEmailChange do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :pending_email_change, :map
    end
  end

  def down do
    alter table(:users) do
      remove :pending_email_change
    end
  end
end
