defmodule Huddlz.Repo.Migrations.TrackSavedLocationReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :group_location_id,
          references(:group_locations,
            column: :id,
            name: "huddlz_group_location_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:huddlz, "huddlz_group_location_id_fkey")

    alter table(:huddlz) do
      remove :group_location_id
    end
  end
end
