defmodule Huddlz.Repo.Migrations.RetainPostNowAttribution do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:social_posts) do
      add :impersonation_id, :uuid

      add :requested_by_id,
          references(:users,
            column: :id,
            name: "social_posts_requested_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:social_posts, "social_posts_requested_by_id_fkey")

    alter table(:social_posts) do
      remove :requested_by_id
      remove :impersonation_id
    end
  end
end
