defmodule Huddlz.Repo.Migrations.SteerSocialPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:social_posts, [:social_connection_id, :huddl_id, :occasion],
                     name: "social_posts_unique_occasion_index"
                   )

    create unique_index(:social_posts, [:social_connection_id, :huddl_id, :occasion],
             name: "social_posts_unique_occasion_index",
             where: "(occasion NOT IN ('moved', 'now'))"
           )

    create table(:social_skips, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :social_connection_id,
          references(:social_connections,
            column: :id,
            name: "social_skips_social_connection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :huddl_id,
          references(:huddlz,
            column: :id,
            name: "social_skips_huddl_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:social_skips, [:social_connection_id, :huddl_id],
             name: "social_skips_unique_skip_index"
           )
  end

  def down do
    drop constraint(:social_skips, "social_skips_huddl_id_fkey")

    drop constraint(:social_skips, "social_skips_social_connection_id_fkey")

    drop_if_exists unique_index(:social_skips, [:social_connection_id, :huddl_id],
                     name: "social_skips_unique_skip_index"
                   )

    drop table(:social_skips)

    drop_if_exists unique_index(:social_posts, [:social_connection_id, :huddl_id, :occasion],
                     name: "social_posts_unique_occasion_index"
                   )

    create unique_index(:social_posts, [:social_connection_id, :huddl_id, :occasion],
             name: "social_posts_unique_occasion_index",
             where: "(occasion <> 'moved')"
           )
  end
end
