defmodule Huddlz.Repo.Migrations.PreserveCopySourceTiming do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz_versions) do
      add :copied_source_ends_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:huddlz_versions) do
      remove :copied_source_ends_at
    end
  end
end
