defmodule Huddlz.Repo.Migrations.AddGroupTimeZone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      add :time_zone, :text, null: false, default: "Etc/UTC"
    end
  end

  def down do
    alter table(:groups) do
      remove :time_zone
    end
  end
end
