defmodule Huddlz.Repo.Migrations.LandingPreferencePoc do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :landing_preference, :text, null: false, default: "agenda"
      add :landing_nudge_declined, :boolean, null: false, default: false
      add :landing_departures, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:users) do
      remove :landing_departures
      remove :landing_nudge_declined
      remove :landing_preference
    end
  end
end
