defmodule Huddlz.Repo.Migrations.AddAgendaLandingPreference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :agenda_landing, :text, null: false, default: "groups"
    end
  end

  def down do
    alter table(:users) do
      remove :agenda_landing
    end
  end
end
