defmodule Huddlz.Repo.Migrations.AddUserOwnerIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:huddl_attendees, [:user_id])

    create index(:groups, [:owner_id])

    create index(:group_members, [:user_id])
  end

  def down do
    drop_if_exists index(:group_members, [:user_id])

    drop_if_exists index(:groups, [:owner_id])

    drop_if_exists index(:huddl_attendees, [:user_id])
  end
end
