defmodule Huddlz.Repo.Migrations.AddLocationTimeZoneFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_locations) do
      add :time_zone, :text
    end

    alter table(:groups) do
      add :time_zone, :text
    end

    alter table(:huddl_templates) do
      add :starts_at_local, :naive_datetime
      add :ends_at_local, :naive_datetime
      add :time_zone, :text
    end

    alter table(:huddlz) do
      add :time_zone, :text
    end

    alter table(:users) do
      add :home_time_zone, :text
    end
  end

  def down do
    alter table(:users) do
      remove :home_time_zone
    end

    alter table(:huddlz) do
      remove :time_zone
    end

    alter table(:huddl_templates) do
      remove :time_zone
      remove :ends_at_local
      remove :starts_at_local
    end

    alter table(:groups) do
      remove :time_zone
    end

    alter table(:group_locations) do
      remove :time_zone
    end
  end
end
