defmodule Huddlz.Repo.Migrations.AddRecurrenceIntervalAndUnit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddl_templates) do
      add :interval, :bigint, null: false, default: 1
      add :unit, :text, null: false, default: "week"
    end

    execute "UPDATE huddl_templates SET unit = 'month' WHERE frequency = 'monthly'"

    alter table(:huddl_templates) do
      remove :frequency
    end
  end

  def down do
    alter table(:huddl_templates) do
      add :frequency, :text, null: false, default: "weekly"
    end

    execute "UPDATE huddl_templates SET frequency = 'monthly' WHERE unit = 'month'"

    alter table(:huddl_templates) do
      remove :unit
      remove :interval
    end
  end
end
