defmodule Huddlz.Repo.Migrations.ConfirmationDestination do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :confirmation_destination, :text
    end
  end

  def down do
    alter table(:users) do
      remove :confirmation_destination
    end
  end
end
