defmodule Huddlz.Repo.Migrations.AccountReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:account_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reason, :text
      add :details, :text
      add :source_type, :text
      add :source_id, :uuid
      add :handled_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :reported_user_id,
          references(:users,
            column: :id,
            name: "account_reports_reported_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :reporter_id,
          references(:users,
            column: :id,
            name: "account_reports_reporter_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :handled_by_id,
          references(:users,
            column: :id,
            name: "account_reports_handled_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:account_reports, [:reporter_id, :reported_user_id],
             name: "account_reports_open_report_index",
             where: "(handled_at IS NULL)"
           )
  end

  def down do
    drop constraint(:account_reports, "account_reports_handled_by_id_fkey")

    drop constraint(:account_reports, "account_reports_reporter_id_fkey")

    drop constraint(:account_reports, "account_reports_reported_user_id_fkey")

    drop_if_exists unique_index(:account_reports, [:reporter_id, :reported_user_id],
                     name: "account_reports_open_report_index"
                   )

    drop table(:account_reports)
  end
end
