defmodule Huddlz.Repo.Migrations.RenameHuddlImagesToHuddlCoverImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:huddl_images), to: table(:huddl_cover_images)

    drop_if_exists index(:huddl_images, [:huddl_id, :inserted_at])

    create index(:huddl_cover_images, [:huddl_id, :inserted_at])

    drop constraint(:huddl_cover_images, "huddl_images_huddl_id_fkey")

    alter table(:huddl_cover_images) do
      modify :huddl_id,
             references(:huddlz,
               column: :id,
               name: "huddl_cover_images_huddl_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute(
      "ALTER INDEX huddl_images_unique_storage_path_index RENAME TO huddl_cover_images_unique_storage_path_index"
    )
  end

  def down do
    execute(
      "ALTER INDEX huddl_cover_images_unique_storage_path_index RENAME TO huddl_images_unique_storage_path_index"
    )

    drop constraint(:huddl_cover_images, "huddl_cover_images_huddl_id_fkey")

    alter table(:huddl_cover_images) do
      modify :huddl_id,
             references(:huddlz,
               column: :id,
               name: "huddl_images_huddl_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists index(:huddl_cover_images, [:huddl_id, :inserted_at])

    create index(:huddl_images, [:huddl_id, :inserted_at])

    rename table(:huddl_cover_images), to: table(:huddl_images)
  end
end
