defmodule Huddlz.Repo.Migrations.RecordHuddlCopySource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz_versions) do
      add :copied_from_id, :uuid
    end
  end

  def down do
    alter table(:huddlz_versions) do
      remove :copied_from_id
    end
  end
end
