defmodule Huddlz.Repo.Migrations.AddWaitlistToHuddlAttendees do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddl_attendees) do
      add :waitlisted_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:huddl_attendees) do
      remove :waitlisted_at
    end
  end
end
