defmodule Huddlz.Repo.Migrations.AddEmailGroupInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_invitations) do
      add :email, :citext
      modify :invitee_id, :uuid, null: true
    end

    flush()

    execute """
    UPDATE group_invitations AS invitation
    SET email = recipient.email
    FROM users AS recipient
    WHERE invitation.invitee_id = recipient.id
    """

    alter table(:group_invitations) do
      modify :email, :citext, null: false
    end

    create index(:group_invitations, [:group_id, :email],
             name: "group_invitations_unique_pending_email_index",
             unique: true,
             where: "status = 'pending'"
           )
  end

  def down do
    drop_if_exists index(:group_invitations, [:group_id, :email],
                     name: "group_invitations_unique_pending_email_index"
                   )

    alter table(:group_invitations) do
      modify :invitee_id, :uuid, null: false
      remove :email
    end
  end
end
