defmodule Huddlz.Repo.Migrations.PersistDisplayTimeZonePreference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :display_time_zone_mode, :text, null: false, default: "automatic"
      add :fixed_display_time_zone, :text
    end
  end

  def down do
    alter table(:users) do
      remove :fixed_display_time_zone
      remove :display_time_zone_mode
    end
  end
end
