defmodule Huddlz.Repo.Migrations.RequireLocationTimeZones do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_locations) do
      modify :time_zone, :text, null: false
    end

    alter table(:groups) do
      modify :location, :text, null: false
      modify :time_zone, :text, null: false
    end

    alter table(:huddl_templates) do
      modify :starts_at_local, :naive_datetime, null: false
      modify :ends_at_local, :naive_datetime, null: false
      modify :time_zone, :text, null: false
    end

    alter table(:huddlz) do
      modify :time_zone, :text, null: false
    end
  end

  def down do
    alter table(:huddlz) do
      modify :time_zone, :text, null: true
    end

    alter table(:huddl_templates) do
      modify :time_zone, :text, null: true
      modify :ends_at_local, :naive_datetime, null: true
      modify :starts_at_local, :naive_datetime, null: true
    end

    alter table(:groups) do
      modify :time_zone, :text, null: true
      modify :location, :text, null: true
    end

    alter table(:group_locations) do
      modify :time_zone, :text, null: true
    end
  end
end
