defmodule Huddlz.Repo.Migrations.AddUserTimeZonePreference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :time_zone_preference, :text
    end
  end

  def down do
    alter table(:users) do
      remove :time_zone_preference
    end
  end
end
