defmodule Huddlz.Repo.Migrations.RequireGroupCoordinates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      modify :latitude, :float, null: false
      modify :longitude, :float, null: false
    end
  end

  def down do
    alter table(:groups) do
      modify :longitude, :float, null: true
      modify :latitude, :float, null: true
    end
  end
end
