defmodule Huddlz.Repo.Migrations.RecordUserSignups do
  @moduledoc """
  Records when each account was created. Accounts from before this column
  existed take their confirmation time as the closest thing on record, and
  the unconfirmed ones the time the migration ran.

  The column itself was autogenerated with `mix ash_postgres.generate_migrations`.
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "UPDATE users SET inserted_at = confirmed_at WHERE confirmed_at IS NOT NULL"
  end

  def down do
    alter table(:users) do
      remove :inserted_at
    end
  end
end
