defmodule Huddlz.Repo.Migrations.AddJoinSuggestionsSentAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :join_suggestions_sent_at, :utc_datetime_usec
    end

    # The join suggestion is only for huddlz that complete from here on.
    # Stamping the ones already completed keeps the scheduler from emailing
    # people about huddlz from before the suggestion existed.
    execute("""
    UPDATE huddlz
    SET join_suggestions_sent_at = completed_at
    WHERE lifecycle_state = 'completed' AND completed_at IS NOT NULL
    """)
  end

  def down do
    alter table(:huddlz) do
      remove :join_suggestions_sent_at
    end
  end
end
