defmodule Huddlz.Repo.Migrations.GroupActivityLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:group_activities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_activities_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :huddl_id,
          references(:huddlz,
            column: :id,
            name: "group_activities_huddl_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "group_activities_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:group_activities, [:group_id, :occurred_at])
  end

  def down do
    drop_if_exists index(:group_activities, [:group_id, :occurred_at])

    drop constraint(:group_activities, "group_activities_user_id_fkey")

    drop constraint(:group_activities, "group_activities_huddl_id_fkey")

    drop constraint(:group_activities, "group_activities_group_id_fkey")

    drop table(:group_activities)
  end
end
