defmodule Huddlz.Repo.Migrations.AddSocialConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:social_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :workspace_name, :text, null: false
      add :channel_name, :text, null: false
      add :webhook_url, :text, null: false
      add :moments, {:array, :text}, null: false, default: []
      add :opening_line, :text
      add :state, :text, null: false, default: "posting"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "social_connections_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :connected_by_id,
          references(:users,
            column: :id,
            name: "social_connections_connected_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:group_activities) do
      add :detail, :text
    end
  end

  def down do
    alter table(:group_activities) do
      remove :detail
    end

    drop constraint(:social_connections, "social_connections_connected_by_id_fkey")

    drop constraint(:social_connections, "social_connections_group_id_fkey")

    drop table(:social_connections)
  end
end
