defmodule Huddlz.Repo.Migrations.AddHuddlLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :lifecycle_state, :text, null: false, default: "published"
      add :published_at, :utc_datetime_usec
      add :cancelled_at, :utc_datetime_usec
      add :cancellation_reason, :text
    end

    execute "UPDATE huddlz SET published_at = inserted_at WHERE published_at IS NULL"
  end

  def down do
    alter table(:huddlz) do
      remove :cancellation_reason
      remove :cancelled_at
      remove :published_at
      remove :lifecycle_state
    end
  end
end
