defmodule Huddlz.Repo.Migrations.UsageMeasurement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:usage_measurement, primary_key: false) do
      add :id, :bigint, null: false, default: 1, primary_key: true
      add :started_on, :date, null: false
    end

    execute("""
    INSERT INTO usage_measurement (id, started_on) VALUES (1, (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::date)
    """)
  end

  def down do
    execute("""
    DELETE FROM usage_measurement WHERE id = 1
    """)

    drop table(:usage_measurement)
  end
end
