defmodule Huddlz.Repo.Migrations.CascadeDestroyGroupsAndHuddls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:huddlz, "huddlz_group_id_fkey")

    alter table(:huddlz) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "huddlz_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:huddl_images, "huddl_images_huddl_id_fkey")

    alter table(:huddl_images) do
      modify :huddl_id,
             references(:huddlz,
               column: :id,
               name: "huddl_images_huddl_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:huddl_attendees, "huddl_attendees_huddl_id_fkey")

    alter table(:huddl_attendees) do
      modify :huddl_id,
             references(:huddlz,
               column: :id,
               name: "huddl_attendees_huddl_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:group_members, "group_members_group_id_fkey")

    alter table(:group_members) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "group_members_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:group_images, "group_images_group_id_fkey")

    alter table(:group_images) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "group_images_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:group_images, "group_images_group_id_fkey")

    alter table(:group_images) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "group_images_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:group_members, "group_members_group_id_fkey")

    alter table(:group_members) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "group_members_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:huddl_attendees, "huddl_attendees_huddl_id_fkey")

    alter table(:huddl_attendees) do
      modify :huddl_id,
             references(:huddlz,
               column: :id,
               name: "huddl_attendees_huddl_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:huddl_images, "huddl_images_huddl_id_fkey")

    alter table(:huddl_images) do
      modify :huddl_id,
             references(:huddlz,
               column: :id,
               name: "huddl_images_huddl_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:huddlz, "huddlz_group_id_fkey")

    alter table(:huddlz) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "huddlz_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
