defmodule Huddlz.Repo.Migrations.AddGroupLocationTimeZone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_locations) do
      add :time_zone, :text
    end

    execute """
    UPDATE group_locations
    SET time_zone = 'America/New_York'
    WHERE time_zone IS NULL
    """

    alter table(:group_locations) do
      modify :time_zone, :text, null: false
    end
  end

  def down do
    alter table(:group_locations) do
      remove :time_zone
    end
  end
end
