defmodule Huddlz.Repo.Migrations.AddHuddlTimeZone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :time_zone, :text
    end
  end

  def down do
    alter table(:huddlz) do
      remove :time_zone
    end
  end
end
