defmodule Huddlz.Repo.Migrations.DefaultGroupTimeZone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      modify :time_zone, :text, default: "America/New_York"
    end
  end

  def down do
    alter table(:groups) do
      modify :time_zone, :text, default: nil
    end
  end
end
