defmodule Huddlz.Repo.Migrations.EmailChangeResendLimits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :email_change_resends, {:array, :bigint}, null: false, default: []
    end
  end

  def down do
    alter table(:users) do
      remove :email_change_resends
    end
  end
end
