defmodule Huddlz.Repo.Migrations.TrackHuddlScheduleHistory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :previous_starts_at, :utc_datetime
      add :previous_time_zone, :text
    end
  end

  def down do
    alter table(:huddlz) do
      remove :previous_time_zone
      remove :previous_starts_at
    end
  end
end
