defmodule Huddlz.Repo.Migrations.LegalAcceptance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :legal_terms_accepted_at, :utc_datetime_usec
      add :legal_documents_version, :text
    end
  end

  def down do
    alter table(:users) do
      remove :legal_documents_version
      remove :legal_terms_accepted_at
    end
  end
end
