defmodule Huddlz.Repo.Migrations.AddApiKeyNamesAndUse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Keys made before names existed are called "API key".
    alter table(:api_keys) do
      add :name, :text, null: false, default: "API key"
      add :last_used_at, :utc_datetime_usec
      add :inserted_at, :utc_datetime_usec
    end

    # Creation times were never stored on the key, but audit history has them
    # for keys made since it started. Keys older than that keep no date rather
    # than a made-up one.
    execute """
    UPDATE api_keys AS k
    SET inserted_at = v.created_at
    FROM (
      SELECT version_source_id, min(version_inserted_at) AS created_at
      FROM api_keys_versions
      WHERE version_action_type = 'create'
      GROUP BY version_source_id
    ) AS v
    WHERE v.version_source_id = k.id
    """

    alter table(:api_keys) do
      modify :name, :text, default: nil
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:api_keys) do
      remove :inserted_at
      remove :last_used_at
      remove :name
    end
  end
end
