defmodule Huddlz.Repo.Migrations.AddApiKeyNamesAndUse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Keys made before names existed are called "API key"; their creation
    # time was never recorded, so they count as created now.
    alter table(:api_keys) do
      add :name, :text, null: false, default: "API key"
      add :last_used_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:api_keys) do
      modify :name, :text, default: nil
    end
  end

  def down do
    alter table(:api_keys) do
      remove :inserted_at
      remove :last_used_at
      remove :name
    end
  end
end
