defmodule Huddlz.Repo.Migrations.AddRecurrenceIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:huddl_templates, [:source_huddl_id],
             name: "huddl_templates_source_huddl_id_index"
           )

    create index(:huddlz, [:huddl_template_id, :starts_at],
             name: "huddlz_huddl_template_id_starts_at_index"
           )
  end

  def down do
    drop_if_exists index(:huddlz, [:huddl_template_id, :starts_at],
                     name: "huddlz_huddl_template_id_starts_at_index"
                   )

    drop_if_exists index(:huddl_templates, [:source_huddl_id],
                     name: "huddl_templates_source_huddl_id_index"
                   )
  end
end
