defmodule Huddlz.Repo.Migrations.RecordJoinSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_members) do
      add :join_source, :text
    end

    alter table(:group_activities) do
      add :source, :text
    end
  end

  def down do
    alter table(:group_activities) do
      remove :source
    end

    alter table(:group_members) do
      remove :join_source
    end
  end
end
