defmodule Huddlz.Repo.Migrations.AddMaxAttendeesToHuddlz do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :max_attendees, :bigint
    end
  end

  def down do
    alter table(:huddlz) do
      remove :max_attendees
    end
  end
end
