defmodule Huddlz.Repo.Migrations.RequireUserOnApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:api_keys, [:user_id])

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    alter table(:api_keys) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             ),
             null: false
    end
  end

  def down do
    drop constraint(:api_keys, "api_keys_user_id_fkey")

    alter table(:api_keys) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true
    end

    drop_if_exists index(:api_keys, [:user_id])
  end
end
