defmodule Huddlz.Repo.Migrations.AddGeolocationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :home_location, :text
      add :home_latitude, :float
      add :home_longitude, :float
    end

    alter table(:huddlz) do
      add :latitude, :float
      add :longitude, :float
    end

    create index(:huddlz, ["ST_MakePoint(longitude, latitude)"],
             name: "huddlz_location_gist_index",
             using: "GIST",
             where: "latitude IS NOT NULL AND longitude IS NOT NULL"
           )

    alter table(:groups) do
      add :latitude, :float
      add :longitude, :float
    end

    create index(:groups, ["ST_MakePoint(longitude, latitude)"],
             name: "groups_location_gist_index",
             using: "GIST",
             where: "latitude IS NOT NULL AND longitude IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:groups, ["ST_MakePoint(longitude, latitude)"],
                     name: "groups_location_gist_index"
                   )

    alter table(:groups) do
      remove :longitude
      remove :latitude
    end

    drop_if_exists index(:huddlz, ["ST_MakePoint(longitude, latitude)"],
                     name: "huddlz_location_gist_index"
                   )

    alter table(:huddlz) do
      remove :longitude
      remove :latitude
    end

    alter table(:users) do
      remove :home_longitude
      remove :home_latitude
      remove :home_location
    end
  end
end
