defmodule Huddlz.Repo.Migrations.CalendarTimeZones do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_locations) do
      add :time_zone, :text
    end

    execute """
    UPDATE group_locations
    SET time_zone = 'America/New_York'
    WHERE time_zone IS NULL
    """

    alter table(:group_locations) do
      modify :time_zone, :text, null: false
    end

    alter table(:groups) do
      add :time_zone, :text
    end

    execute "UPDATE groups SET time_zone = 'America/New_York' WHERE time_zone IS NULL"

    alter table(:groups) do
      modify :time_zone, :text, null: false, default: "America/New_York"
    end

    alter table(:huddlz) do
      add :time_zone, :text
    end

    execute "UPDATE huddlz SET time_zone = 'America/New_York' WHERE time_zone IS NULL"

    alter table(:huddlz) do
      modify :time_zone, :text, null: false
    end

    alter table(:huddl_templates) do
      add :starts_at_local, :naive_datetime
      add :ends_at_local, :naive_datetime
      add :time_zone, :text
    end

    execute """
    UPDATE huddl_templates AS templates
    SET starts_at_local =
          (source.starts_at AT TIME ZONE 'UTC') AT TIME ZONE source.time_zone,
        ends_at_local =
          (source.ends_at AT TIME ZONE 'UTC') AT TIME ZONE source.time_zone,
        time_zone = source.time_zone
    FROM huddlz AS source
    WHERE source.id = (
      SELECT candidate.id
      FROM huddlz AS candidate
      WHERE candidate.huddl_template_id = templates.id
      ORDER BY candidate.starts_at ASC
      LIMIT 1
    )
    """

    execute """
    UPDATE huddl_templates
    SET starts_at_local = repeat_until,
        ends_at_local = repeat_until + INTERVAL '1 hour',
        time_zone = 'America/New_York'
    WHERE starts_at_local IS NULL
    """

    alter table(:huddl_templates) do
      modify :starts_at_local, :naive_datetime, null: false
      modify :ends_at_local, :naive_datetime, null: false
      modify :time_zone, :text, null: false
    end

    alter table(:users) do
      add :home_time_zone, :text
      add :display_time_zone_mode, :text, null: false, default: "automatic"
      add :fixed_display_time_zone, :text
    end

    execute """
    UPDATE users
    SET home_time_zone = 'America/New_York'
    WHERE home_location IS NOT NULL AND home_time_zone IS NULL
    """
  end

  def down do
    alter table(:users) do
      remove :fixed_display_time_zone
      remove :display_time_zone_mode
      remove :home_time_zone
    end

    alter table(:huddlz) do
      remove :time_zone
    end

    alter table(:huddl_templates) do
      remove :time_zone
      remove :ends_at_local
      remove :starts_at_local
    end

    alter table(:groups) do
      remove :time_zone
    end

    alter table(:group_locations) do
      remove :time_zone
    end
  end
end
