defmodule Huddlz.Repo.Migrations.RemoveRsvpCountColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      remove :rsvp_count
    end
  end

  def down do
    alter table(:huddlz) do
      add :rsvp_count, :bigint, null: false, default: 0
    end
  end
end
