defmodule Huddlz.Repo.Migrations.AddHuddlLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :lifecycle_state, :text, null: false, default: "published"
      add :published_at, :utc_datetime_usec
      add :cancelled_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :cancellation_reason, :text

      add :published_by_id,
          references(:users,
            column: :id,
            name: "huddlz_published_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :cancelled_by_id,
          references(:users,
            column: :id,
            name: "huddlz_cancelled_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    execute("""
    UPDATE huddlz
    SET published_at = inserted_at,
        published_by_id = creator_id,
        lifecycle_state = CASE
          WHEN ends_at <= NOW() THEN 'completed'
          ELSE 'published'
        END,
        completed_at = CASE
          WHEN ends_at <= NOW() THEN ends_at
          ELSE NULL
        END
    """)

    create constraint(:huddlz, :huddlz_valid_lifecycle_state,
             check: """
               lifecycle_state IN ('draft', 'published', 'cancelled', 'completed')
             """
           )
  end

  def down do
    drop_if_exists constraint(:huddlz, :huddlz_valid_lifecycle_state)

    drop constraint(:huddlz, "huddlz_published_by_id_fkey")

    drop constraint(:huddlz, "huddlz_cancelled_by_id_fkey")

    alter table(:huddlz) do
      remove :cancelled_by_id
      remove :published_by_id
      remove :cancellation_reason
      remove :completed_at
      remove :cancelled_at
      remove :published_at
      remove :lifecycle_state
    end
  end
end
