defmodule Huddlz.Repo.Migrations.AddPlaceIdToLocations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_locations) do
      add :place_id, :text
    end

    alter table(:huddlz) do
      add :place_id, :text
    end
  end

  def down do
    alter table(:huddlz) do
      remove :place_id
    end

    alter table(:group_locations) do
      remove :place_id
    end
  end
end
