defmodule Huddlz.Repo.Migrations.ReminderSentColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :reminder_24h_sent_at, :utc_datetime_usec
      add :reminder_1h_sent_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:huddlz) do
      remove :reminder_1h_sent_at
      remove :reminder_24h_sent_at
    end
  end
end
