defmodule Huddlz.Repo.Migrations.PocELandingChoice do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :landing_choice, :text, null: false, default: "unasked"
    end
  end

  def down do
    alter table(:users) do
      remove :landing_choice
    end
  end
end
