defmodule Huddlz.Repo.Migrations.RemoveUnitFromGroupLocations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:group_locations, [:group_id, :name, :unit],
                     name: "group_locations_unique_name_and_unit_per_group_index"
                   )

    alter table(:group_locations) do
      remove :unit
    end
  end

  def down do
    alter table(:group_locations) do
      add :unit, :text
    end

    create unique_index(:group_locations, [:group_id, :name, :unit],
             name: "group_locations_unique_name_and_unit_per_group_index",
             nulls_distinct: false
           )
  end
end
