defmodule Huddlz.Repo.Migrations.AddDiscordDestinationIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:social_connections) do
      add :discord_guild_id, :text
      add :discord_channel_id, :text
    end
  end

  def down do
    alter table(:social_connections) do
      remove :discord_channel_id
      remove :discord_guild_id
    end
  end
end
