defmodule Huddlz.Repo.Migrations.RecordTurnout do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :turnout_in_room, :bigint
      add :turnout_on_call, :bigint
      add :turnout_recorded_at, :utc_datetime_usec
      add :turnout_skipped_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:huddlz) do
      remove :turnout_skipped_at
      remove :turnout_recorded_at
      remove :turnout_on_call
      remove :turnout_in_room
    end
  end
end
