defmodule Huddlz.Repo.Migrations.Impersonations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_activities) do
      add :impersonation_id, :uuid
    end

    create table(:impersonations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ended_at, :utc_datetime_usec

      add :admin_id,
          references(:users,
            column: :id,
            name: "impersonations_admin_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "impersonations_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:impersonations, "impersonations_user_id_fkey")

    drop constraint(:impersonations, "impersonations_admin_id_fkey")

    drop table(:impersonations)

    alter table(:group_activities) do
      remove :impersonation_id
    end
  end
end
