defmodule Huddlz.Repo.Migrations.ActiveDays do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:active_days, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :day, :date, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "active_days_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:active_days, [:user_id, :day], name: "active_days_one_per_day_index")

    create index(:active_days, [:day])
  end

  def down do
    drop_if_exists index(:active_days, [:day])

    drop constraint(:active_days, "active_days_user_id_fkey")

    drop_if_exists unique_index(:active_days, [:user_id, :day],
                     name: "active_days_one_per_day_index"
                   )

    drop table(:active_days)
  end
end
