defmodule Huddlz.Repo.Migrations.AddHuddlLifecycleIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:huddlz, [:lifecycle_state, :ends_at],
             name: "huddlz_lifecycle_state_ends_at_index"
           )
  end

  def down do
    drop_if_exists index(:huddlz, [:lifecycle_state, :ends_at],
                     name: "huddlz_lifecycle_state_ends_at_index"
                   )
  end
end
