defmodule Huddlz.Repo.Migrations.AddGroupInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:group_invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"
      add :status, :text, null: false, default: "pending"
      add :expires_at, :utc_datetime_usec, null: false
      add :responded_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_invitations_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :invitee_id,
          references(:users,
            column: :id,
            name: "group_invitations_invitee_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :inviter_id,
          references(:users,
            column: :id,
            name: "group_invitations_inviter_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:group_invitations, [:group_id, :status, :inserted_at])

    create index(:group_invitations, [:invitee_id, :status, :inserted_at])

    create index(:group_invitations, [:group_id, :invitee_id],
             name: "group_invitations_unique_pending_index",
             unique: true,
             where: "status = 'pending'"
           )
  end

  def down do
    drop constraint(:group_invitations, "group_invitations_group_id_fkey")

    drop constraint(:group_invitations, "group_invitations_invitee_id_fkey")

    drop constraint(:group_invitations, "group_invitations_inviter_id_fkey")

    drop_if_exists index(:group_invitations, [:group_id, :invitee_id],
                     name: "group_invitations_unique_pending_index"
                   )

    drop_if_exists index(:group_invitations, [:invitee_id, :status, :inserted_at])

    drop_if_exists index(:group_invitations, [:group_id, :status, :inserted_at])

    drop table(:group_invitations)
  end
end
