defmodule Huddlz.Repo.Migrations.AddGroupLocations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:group_locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :address, :text, null: false
      add :latitude, :float, null: false
      add :longitude, :float, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_locations_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:group_locations, [:group_id, :name],
             name: "group_locations_unique_name_per_group_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(:group_locations, [:group_id, :name],
                     name: "group_locations_unique_name_per_group_index"
                   )

    drop constraint(:group_locations, "group_locations_group_id_fkey")

    drop table(:group_locations)
  end
end
