#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Registers the huddlz app on Slack and Discord so groups can connect a
# place (social connections), then records the four OAuth values for one
# environment: .dev.env for local development, Fly secrets for production.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Where the four values go. Development: .dev.env, the file mix setup makes
# from .dev.env.example. Production: Fly secrets on the huddlz app; the
# values are staged in memory and set together in the last stage.
TARGET=""            # dev | prod
HOST=""              # the https origin the platforms send people back to
FLY_APP="${FLY_APP:-huddlz}"

# set_fly_secret NAME VALUE stages a Fly secret; flush_fly_secrets sets them
# in one `fly secrets set` so the app restarts once, not four times.
FLY_STAGED=()
set_fly_secret() { FLY_STAGED+=("$1=$2"); printf '  %s✓ staged%s Fly secret %s\n' "$GREEN" "$RESET" "$1"; }
flush_fly_secrets() {
  (( ${#FLY_STAGED[@]} )) || return 0
  if command -v fly >/dev/null 2>&1 && fly auth whoami >/dev/null 2>&1; then
    if fly secrets set --app "$FLY_APP" "${FLY_STAGED[@]}" >/dev/null 2>&1; then
      for pair in "${FLY_STAGED[@]}"; do WRITTEN_SECRET+=("Fly ${pair%%=*}"); done
      printf '  %s✓ set%s %s Fly secret(s) on %s\n' "$GREEN" "$RESET" "${#FLY_STAGED[@]}" "$FLY_APP"
      return
    fi
  fi
  for pair in "${FLY_STAGED[@]}"; do
    SKIPPED+=("Fly secret ${pair%%=*} (set it by hand: fly secrets set --app $FLY_APP ${pair%%=*}=…)")
  done
  warn "fly not ready; the Fly secrets were not set"
}

# record KEY VALUE puts a value where the chosen environment keeps it.
record() {
  case "$TARGET" in
    dev)  write_env "$1" "$2" ;;
    prod) set_fly_secret "$1" "$2" ;;
  esac
}

banner "huddlz social connections: Slack and Discord apps"

# ── 1. Which environment ──────────────────────────────────────────────────
stage "Which environment"
say "Each environment needs its own Slack app and Discord application,"
say "because each one pins the redirect URL people are sent back to."
say ""
step "1  Development: values go to .dev.env; Slack needs an https tunnel to localhost."
step "2  Production:  values become Fly secrets on the '$FLY_APP' app (huddlz.com)."
printf '  %sPick 1 or 2:%s ' "$BOLD" "$RESET"
read -r choice || true
case "$choice" in
  1) TARGET=dev;  ENV_FILE=".dev.env" ;;
  2) TARGET=prod ;;
  *) printf '  %sPick 1 or 2 and re-run.%s\n' "$RED" "$RESET"; exit 1 ;;
esac

if [[ "$TARGET" == dev ]]; then
  say ""
  say "Slack refuses http and localhost redirect URLs, so run a tunnel first,"
  say "for example:  ngrok http 4000   (or cloudflared tunnel --url http://localhost:4000)"
  say "and paste the https origin it gives you. Discord is fine with the tunnel too."
  ask SOCIAL_DEV_ORIGIN "https origin of the tunnel (e.g. https://abc123.ngrok-free.app):"
  HOST="${SOCIAL_DEV_ORIGIN%/}"
  write_env SOCIAL_DEV_ORIGIN "$HOST"
  note "PHX_HOST in .dev.env stays localhost; the tunnel forwards to it. If the app"
  note "rejects the tunnel's Host header, set PHX_CHECK_ORIGIN=false in .dev.env."
else
  HOST="https://huddlz.com"
  say ""
  say "Redirect URLs will use $HOST."
fi
say ""
say "Slack callback:   $HOST/social/slack/callback"
say "Discord callback: $HOST/social/discord/callback"
pause

# ── 2. Slack: create the app ──────────────────────────────────────────────
stage "Slack: create the app"
open_url "https://api.slack.com/apps?new_app=1"
step "Choose 'From scratch'."
step "App Name: huddlz (add ' dev' for the development app)."
step "Pick the workspace you develop or test in; this only decides where the app is owned."
step "Click Create App."
pause "Done? Press Enter."

# ── 3. Slack: client id and secret ────────────────────────────────────────
stage "Slack: client id and secret"
say "You should be on Basic Information. Scroll to App Credentials."
open_url "https://api.slack.com/apps"
step "Copy the Client ID."
ask SLACK_CLIENT_ID "Paste the Slack Client ID:"
step "Click Show next to Client Secret and copy it."
ask_secret SLACK_CLIENT_SECRET "Paste the Slack Client Secret (hidden):"
record SLACK_CLIENT_ID "$SLACK_CLIENT_ID"
record SLACK_CLIENT_SECRET "$SLACK_CLIENT_SECRET"

# ── 4. Slack: redirect URL and scope ──────────────────────────────────────
stage "Slack: redirect URL and scope"
say "In the left menu open OAuth & Permissions."
step "Redirect URLs → Add New Redirect URL:"
say "      $HOST/social/slack/callback"
step "Click Add, then Save URLs."
step "Scroll to Scopes → Bot Token Scopes → Add an OAuth Scope → incoming-webhook."
note "That is the only scope huddlz asks for: it posts to one channel the person picks."
pause "Both saved? Press Enter."

# ── 5. Slack: let other workspaces install it ─────────────────────────────
stage "Slack: distribution"
if [[ "$TARGET" == prod ]]; then
  say "Groups connect their own workspaces, so the app must be installable outside yours."
  say "In the left menu open Manage Distribution."
  step "Under 'Share Your App with Other Workspaces', complete each checklist item"
  step "(remove hard-coded information, confirm the redirect URL) and click"
  step "Activate Public Distribution."
  note "No App Directory listing or review is needed for this; distribution is enough."
  pause "Activated? Press Enter."
else
  say "For development the app only needs to work in the workspace that owns it,"
  say "so nothing to do here. Activate public distribution on the production app instead."
  pause
fi

# ── 6. Discord: application and credentials ───────────────────────────────
stage "Discord: application and credentials"
open_url "https://discord.com/developers/applications"
step "Click New Application, name it huddlz (or 'huddlz dev'), agree, Create."
step "In the left menu open OAuth2."
step "Copy the Client ID."
ask DISCORD_CLIENT_ID "Paste the Discord Client ID:"
step "Click Reset Secret, confirm, and copy the secret (Discord shows it once)."
ask_secret DISCORD_CLIENT_SECRET "Paste the Discord Client Secret (hidden):"
record DISCORD_CLIENT_ID "$DISCORD_CLIENT_ID"
record DISCORD_CLIENT_SECRET "$DISCORD_CLIENT_SECRET"

# ── 7. Discord: redirect URL ──────────────────────────────────────────────
stage "Discord: redirect URL"
say "Still on the OAuth2 page, under Redirects:"
step "Add Redirect:  $HOST/social/discord/callback"
step "Save Changes."
note "No scopes to configure here: huddlz asks for webhook.incoming in the link it"
note "builds, and Discord's own screen picks the server and channel."
pause "Saved? Press Enter."

# ── 8. Write the values and check ─────────────────────────────────────────
stage "Record the values"
if [[ "$TARGET" == prod ]]; then
  say "Setting the four Fly secrets on '$FLY_APP' restarts the app once."
  if confirm "Set them now?"; then
    flush_fly_secrets
  else
    for pair in "${FLY_STAGED[@]}"; do SKIPPED+=("Fly secret ${pair%%=*}"); done
    warn "not set; the values were not saved anywhere"
  fi
else
  say "The values are in $ENV_FILE. Restart the dev server to pick them up."
fi
say ""
say "To try it: open a public group you own → Organize → Social → Connect a place."
say "Slack's or Discord's screen should open, and after choosing a channel you land"
say "back on the Social tab with the schedule sheet open. Send a test post from there."

finish
